### ISSUE TITLE
docker-compose: "caso queira utilizar MongoDB"

### ISSUE THREAD

**Issue by victorvf** [teresinahc/api-denuncia-de-aglomeracao#10]
#### Adicionar dentro do arquivo docker-compose.yml:
caso futuramente vá querer utilizar o mongo dentro da api, basta realizar isto:
```
services: //Esta linha já existe
    mongo:
        image: mongo:4.2.6
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
          - "27017:27017"
        volumes:
          - ./mongoDb:/data/db
    node: //Esta linha já existe
        depends_on:
          - mongo //Adicionar somente está linha
```
